version: '3.8'

# 開発環境用に簡略化したDocker Compose設定
services:
  # フロントエンド
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000

  # APIゲートウェイとバックエンドサービスを統合したテストサーバー
  backend:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/api-gateway:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=true
      - AUTH_SERVICE_URL=http://backend:8001  # 同じコンテナでサービスを模倂
      - USER_SERVICE_URL=http://backend:8001
      - DOC_SERVICE_URL=http://backend:8001
      - RAG_SERVICE_URL=http://backend:8001
      - LLM_SERVICE_URL=http://backend:8001
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  # Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
